log:
  level: debug
  format: console
kafka:
  url: localhost:9092
  env: staging
rpcs:
  ethereum:
    full:
      - https://hopeful-leakey:spud-chaste-trance-width-upward-harbor@nd-334-593-626.p2pify.com
      - wss://hopeful-leakey:spud-chaste-trance-width-upward-harbor@ws-nd-334-593-626.p2pify.com
      - https://sparkling-wild-water.quiknode.pro/886d6e59b11a916a403259ad83de327d15ad0c33/
      - wss://sparkling-wild-water.quiknode.pro/886d6e59b11a916a403259ad83de327d15ad0c33/
    archival:
      - https://sparkling-wild-water.quiknode.pro/886d6e59b11a916a403259ad83de327d15ad0c33/
