name: Nakji Connector

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/nakji_connector.yml'
  pull_request:
    branches: [ none ]
    paths:
      - '**'

defaults:
  run:
    shell: bash

jobs:

  # https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3

        # Run jobs.build for every directory
      - id: matrix
        run: |
          echo "::set-output name=value::$(ls | jq -R -s -c 'split("\n")[:-1]'))" # TODO: ls only directories that changed

  build:
    needs: [ setup ] # test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}

    # Add "id-token" with the intended permissions. Required with google-github-actions/auth.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - run: |
        echo "${{ matrix.value }}"

    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run read-yaml action
      id: yaml-data
      uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
      with:
        file: '${{matrix.value}}/manifest.yaml'          # File to read from
        key-path: '["version"]' # Access the runs key then the using key and retuns the value.

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_REPO }}/${{ matrix.value }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          # output 0.1.2
          type=semver,pattern={{version}},value=${{ steps.yaml-data.outputs.data }}
          # output 0.1
          type=semver,pattern={{major}}.{{minor}},value=${{ steps.yaml-data.outputs.data }}
          # disabled if major zero
          type=semver,pattern={{major}},enable=${{ !startsWith(steps.yaml-data.outputs.data, '0.') }}
        labels: |
          maintainer=CrazyMax
          org.opencontainers.image.title=${{ matrix.value }}
          org.opencontainers.image.description=

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - uses: 'docker/login-action@v1'
      with:
        registry:  ${{ secrets.DOCKER_REPO }}
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Login to google Container Registry
      run: |-
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin ${{ secrets.DOCKER_REPO }}

    - name: Build and push
      uses: docker/build-push-action@v2
      env:
        BRANCH: ${{ env.GITHUB_REF_SLUG }}
      with:
        build-args: |
          VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          BUILD=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
        context: ${{ matrix.value }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: 'C03DL2A73SB' #devops-alerts
        # For posting a simple plain text message
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n${{ steps.meta.outputs.tags }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  #deploy:
    #needs: build
    #runs-on: 'ubuntu-latest'
    #steps:
    #- uses: actions/checkout@v1

    #- name: Lint Helm
      #uses: WyriHaximus/github-action-helm3@v2
      #with:
        #exec: helm lint devops/k8s/helm-charts/analytics

    #- name: Install doctl
      #uses: digitalocean/action-doctl@v2
      #with:
        #token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    #- name: Save DigitalOcean kubeconfig
      #run: doctl kubernetes cluster kubeconfig save ${{ secrets.K8S_CLUSTER_NAME }}

    #- name: Set kubectl namespace
      #if: github.ref == 'refs/heads/master'
      #run: |
        #kubectl config set-context --current --namespace=prod

    #- name: Set kubectl namespace
      #if: github.ref == 'refs/heads/staging'
      #run: |
        #kubectl config set-context --current --namespace=staging

    ##- name: Rollout updated image
      ##run: |
        ##kubectl rollout restart $(kubectl get deployments --selector "app=analytics-client" --output=name)

    #- name: Send Telegram notification
      #uses: appleboy/telegram-action@master
      #with:
        #to: ${{ secrets.TELEGRAM_TO }}
        #token: ${{ secrets.TELEGRAM_TOKEN }}
        #message: |
          #Github action ${{ github.workflow }} (${{github.job}}) finished.
          #More information at https://github.com/blep-ai/blep/actions/runs/${{github.run_id}}.
